### ISSUE TITLE
Different behavior of domain.get('') in dev and prod env 

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10553]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. SomeDomain.get('')  // empty string
2. Execute in dev env -- return null
3. Build war 
4. start in tomcat 

### Expected Behaviour

Return null, like in dev env. Behavior for this simple operation should be same in dev and prod

### Actual Behaviour

Exception thrown only in prod

java.lang.IllegalArgumentException: id to load is required for loading
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:93)
at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:63)
at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2759)
at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2741)
at org.hibernate.internal.SessionImpl.get(SessionImpl.java:978)
at org.grails.orm.hibernate.GrailsHibernateTemplate$2.doInHibernate(GrailsHibernateTemplate.java:349)
at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:286)
at org.grails.orm.hibernate.GrailsHibernateTemplate.get(GrailsHibernateTemplate.java:346)
at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.get(AbstractHibernateGormStaticApi.groovy:89)
at org.grails.datastore.gorm.GormEntity$Trait$Helper.get(GormEntity.groovy:518)
at org.grails.datastore.gorm.GormEntity$Trait$Helper$get$5.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.grails.datastore.gorm.GormEntity$Trait$Helper$get$5.call(Unknown Source)
at Domain.get(Domain.groovy)

### Environment Information

- **Operating System**: Ubuntu 14
- **Grails Version:** 3.2.8
- **JDK Version:** 8.0.121
- **Container Version (If Applicable):** Tomcat

**Comment by demon101** [comment]
linked #10538

**Comment by jameskleeh** [comment]
I don't see any difference in behavior between dev and prod

**Comment by jameskleeh** [comment]
This has been fixed already, it just hasn't been released.

**Comment by demon101** [comment]
@jameskleeh in which issue???

**Comment by jameskleeh** [comment]
@demon101  https://github.com/grails/grails-core/issues/10538

**Comment by demon101** [comment]
@jameskleeh  I'm testing on Grails 3.2.8 . This version includes #10538 . Bug still here

**Comment by jameskleeh** [comment]
@demon101 That version does not include the relevant commit. See https://github.com/grails/grails-data-mapping/commits/6.0.x. There hasn't been a release since https://github.com/grails/grails-data-mapping/commit/ab0e09971b11c15031d4c65b51d687640b4ee520
