### ISSUE TITLE
Message sources from exploded plugins in multi-project setup are not loaded with Gradle 4+

### ISSUE THREAD

**Issue by davidkron** [grails/grails-core#11099]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Description

I have a multi-project setup with multiple grails plugins and a single main application. I wanted to upgrade to Gradle 4, but every message source placed in one of the plugins will not be loaded when starting the main application.

The main application loads the plugins like this:
```
grails {
    pathingJar = true
    exploded = true
    plugins {
        compile project(':plugin1')
        compile project(':pulgin2')
    }
}
```

Also hot reloading has to be enabled in gradle.properties (inside plugin): 
```
exploded=true
```

### Steps to Reproduce

1. create multi-project gradle build with a grails plugin and a grails application
2. add plugin as a dependency to application
3. configure plugin for hot reloading (exploded=true in gradle.properties inside plugin)
4. add custom entry in messages.properties inside plugin
5. use the created message property inside application, e.g. in a GSP
6. start application

### Expected Behaviour

Since application has a dependency to the plugin, every message property should be available in the main application.

### Actual Behaviour

Message source from plugin is not loaded. The behavior is likely due to the changes of the build output folder in Gradle 4 from `build/classes/main` to `build/classes/groovy/main`.

With some debugging I discovered the culprit to be the method `findRootResourcesURL` in the class `grails.io.IOUtils`, specifically this line:
```
rootPath = rootPath.replace('/build/classes/', '/build/resources/')
```

With the new output folder from Gradle, this will produce a path like `*/build/resources/groovy/main` instead of `*/build/resources/main`.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.8
- **JDK Version:** 8

**Comment by zyro23** [comment]
seeing the same issue. looks like message codes are resolved when running the built `war` but not running locally (`bootRun`)

**Comment by bruno-lopes** [comment]
I can confirm the same happens on Grails 3.3.9. Is there any workaround available?

**Comment by zyro23** [comment]
well we currently do this in the affected sub-project(s) (`build.gradle`):
```groovy
// FIXME: grails-core#11099 - this workaround does not support reloading
task copyDevelopmentMessageProperties(type: Copy) {
	from "grails-app/i18n"
	into "${buildDir}/resources/groovy/main"
}
processResources.finalizedBy copyDevelopmentMessageProperties

```

**Comment by bruno-lopes** [comment]
@zyro23, very thanks for your response. With this solution, isn't possible to reload the changes in messages.properties, because they are copied in build time, right? I think I'll wait for the fix, and use Gradle 3.5 for now.

**Comment by davidkron** [comment]
I recently tested one of our application with Grails 4.0.0.BUILD-SNAPSHOT. Grails 4 will use Gradle 5 as a default. The problem described in this issue is still present in the Grails 4 snapshot.

**Comment by demon101** [comment]
@puneetbehl is it fixed?

**Comment by puneetbehl** [comment]
yes, this has been fixed.
