### ISSUE TITLE
Grails 5.0.3 and 5.1.1 - invalid dependency on parent profile

### ISSUE THREAD

**Issue by jnunderwood** [grails/grails-core#12279]
I am unable to run `grails` commands in an app based on a custom profile. This used to work in grails v4.0.x.

### Steps to Reproduce

1. Create a custom profile: `grails create-profile myprofile`
2. Add this dependency to `build.gradle`: `profileRuntimeOnly "org.grails.profiles:web:5.0.2"`
3. Create an app which uses that profile: `grails create-app myapp-profile myprofile`
4. Run any `grails` command

### Expected Behaviour

Grails commands should work without errors.

### Actual Behaviour

Running any grails commands, including just `grails` by itself, results in an error:

```
| Error Error occurred running Grails CLI: Profile [org.grails.profiles:web:5.0.2] declares an invalid dependency on parent profile [org.grails.profiles:web:5.0.2]
```

### Environment Information

- **Operating System**: Ubuntu 20.04 on WSL2
- **Grails Version:** 5.0.3 and 5.1.1
- **JDK Version:** 11.0.13-tem
- **Container Version (If Applicable):** N/A

**Comment by puneetbehl** [comment]
It seems there are some issues when we published to Maven Central. Please check https://issues.sonatype.org/browse/OSSRH-76440 for more details.

**Comment by puneetbehl** [comment]
Could you please verify if this is resolved now?

**Comment by jnunderwood** [comment]
> Could you please verify if this is resolved now?

When my profile is based on Grails 5.1.1, I am able to run `gradle clean classes` successfully. However, when I run `grails` or `grails clean`, I get the same error message as before.

**Comment by carlosorrego** [comment]
i am having this same error. GRails version 5.2.1 upgraded from 5.1.8. Any help i woul appreciate it

**Comment by jnunderwood** [comment]
@puneetbehl Hello. Is there any update on this issue? It is still a problem. Thank you.

**Comment by puneetbehl** [comment]
This is not a bug in Grails. Earlier this was handled by the Grails Profile Publish plugin and now this is not handled automatically. The Grails Shell looks for the profile JAR which seems to be missing in this case. So, you have to correctly configure the Gradle maven-publish plugin and publish to your local (./gradlew publishToMavenLocal) or Maven Central. 

Here is an example:

```
buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:${project.grailsGradlePluginVersion}"
    }
}

apply plugin: "org.grails.grails-profile"
apply plugin: "maven-publish"

group 'org.grails.profiles'
version '1.0.0'

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}  

dependencies {
    profileRuntimeOnly "org.grails.profiles:web:5.0.5"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'org.grails.profiles'
            artifactId = 'helloprofile'
            version = '1.0.0'

            def jar = project.tasks.findByName("jar")
            if (jar != null) {
                artifact project.tasks.findByName("jar")
            }

            def sourcesJar = tasks.findByName("sourcesJar")
            if (sourcesJar != null) {
                artifact sourcesJar
            }
            def javadocJar = tasks.findByName("javadocJar")
            if (javadocJar != null) {
                artifact javadocJar
            }

        }
    }
}
```

Ref: https://github.com/puneetbehl/custom-profile
