### ISSUE TITLE
7.0.0-SNAPSHOT BUG - pom files are incorrectly being resolved in classLoader

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13983]
### Bug

.pom files are now incorrectly being resolved in the classLoader and this is breaking resource resolution as there should only be jars

```
Failed to load manifest entries from jar file '/Users/user/.gradle/caches/modules-2/files-2.1/org.graalvm.js/js-community/24.1.1/3e874f113d724138c39287df69e5cfb7e5fcf700/js-community-24.1.1.pom': java.util.zip.ZipException: zip END header not found

java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1649)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657)
```

```groovy
new PathMatchingResourcePatternResolver(grailsApplication.classLoader).getResources("classpath*:messages_*.properties")
```

Simple Example App (1 line of code + gradle.properties change from forge create-app)
https://github.com/codeconsole/grails-resource-bug

This was broken AFTER the release of M1 as M1 works fine. 

### Version

7.0.0-SNAPSHOT

**Comment by jamesfredley** [comment]
js-community-24.1.1.pom is coming from:

https://repo1.maven.org/maven2/org/graalvm/js/js/24.1.1/js-24.1.1.pom

```
<dependency>
<groupId>org.graalvm.js</groupId>
<artifactId>js-community</artifactId>
<version>24.1.1</version>
<type>pom</type>
<scope>runtime</scope>
</dependency>
```

**Comment by codeconsole** [comment]
```
+--- com.bertramlabs.plugins:asset-pipeline-grails:5.0.5
|    +--- org.grails:grails-core -> 7.0.0-SNAPSHOT (*)
|    +--- org.grails:grails-logging -> 7.0.0-SNAPSHOT (*)
|    +--- org.grails:grails-plugin-url-mappings -> 7.0.0-SNAPSHOT (*)
|    +--- com.github.ben-manes.caffeine:caffeine:3.1.8 (*)
|    +--- org.grails:grails-web-boot -> 7.0.0-SNAPSHOT (*)
|    +--- org.springframework.boot:spring-boot-autoconfigure -> 3.4.1 (*)
|    +--- org.springframework.boot:spring-boot-starter-logging -> 3.4.1 (*)
|    +--- org.springframework.boot:spring-boot-starter-validation -> 3.4.1 (*)
|    \--- com.bertramlabs.plugins:asset-pipeline-core:5.0.5
|         +--- org.graalvm.sdk:graal-sdk:22.0.0.2 -> 24.1.1
|         |    +--- org.graalvm.sdk:collections:24.1.1
|         |    +--- org.graalvm.sdk:nativeimage:24.1.1
|         |    |    \--- org.graalvm.sdk:word:24.1.1
|         |    +--- org.graalvm.polyglot:polyglot:24.1.1
|         |    |    +--- org.graalvm.sdk:collections:24.1.1
|         |    |    \--- org.graalvm.sdk:nativeimage:24.1.1 (*)
|         |    \--- org.graalvm.sdk:word:24.1.1
|         +--- org.graalvm.js:js:22.0.0.2 -> 24.1.1
|         |    +--- org.graalvm.js:js-community:24.1.1
|         |    |    +--- org.graalvm.js:js-language:24.1.1
|         |    |    |    +--- org.graalvm.regex:regex:24.1.1
|         |    |    |    |    +--- org.graalvm.truffle:truffle-api:24.1.1
|         |    |    |    |    |    +--- org.graalvm.sdk:collections:24.1.1
|         |    |    |    |    |    +--- org.graalvm.sdk:nativeimage:24.1.1 (*)
|         |    |    |    |    |    \--- org.graalvm.polyglot:polyglot:24.1.1 (*)
|         |    |    |    |    \--- org.graalvm.shadowed:icu4j:24.1.1
|         |    |    |    +--- org.graalvm.truffle:truffle-api:24.1.1 (*)
|         |    |    |    +--- org.graalvm.polyglot:polyglot:24.1.1 (*)
|         |    |    |    \--- org.graalvm.shadowed:icu4j:24.1.1
|         |    |    \--- org.graalvm.truffle:truffle-runtime:24.1.1
|         |    |         +--- org.graalvm.sdk:jniutils:24.1.1
|         |    |         |    +--- org.graalvm.sdk:collections:24.1.1
|         |    |         |    \--- org.graalvm.sdk:nativeimage:24.1.1 (*)
|         |    |         +--- org.graalvm.truffle:truffle-api:24.1.1 (*)
|         |    |         \--- org.graalvm.truffle:truffle-compiler:24.1.1
|         |    \--- org.graalvm.truffle:truffle-enterprise:24.1.1
|         |         +--- org.graalvm.truffle:truffle-compiler:24.1.1
|         |         +--- org.graalvm.truffle:truffle-runtime:24.1.1 (*)
|         |         +--- org.graalvm.sdk:jniutils:24.1.1 (*)
|         |         \--- org.graalvm.sdk:nativebridge:24.1.1
|         |              \--- org.graalvm.sdk:jniutils:24.1.1 (*)
|         +--- org.graalvm.js:js-scriptengine:22.0.0.2 -> 24.1.1
|         |    \--- org.graalvm.polyglot:polyglot:24.1.1 (*)
|         \--- org.slf4j:slf4j-api:1.7.28 -> 2.0.16
```

**Comment by codeconsole** [comment]
The following is being resolved with Asset Pipeline 5.0.4.   No graalvm dependencies should be in the class path. 

```
git clone https://github.com/codeconsole/grails-resource-bug
cd grails-resource-bug
gradle clean dependencies|grep graalvm 
# NO RESULTS!!!
```

change logback xml
```xml
<logger name="org.springframework.core.io.support" level="TRACE"/>
```
```
gradle clean bootRun|grep graalvm
# lots of results!!!
```
notice
```
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.graalvm.js/js-community/24.1.1/3e874f113d724138c39287df69e5cfb7e5fcf700/js-community-24.1.1.pom!/], 
```
toward the end of

```
2025-01-30T15:16:56.410-08:00 TRACE 49667 --- [           main] .i.s.PathMatchingResourcePatternResolver : Resolved class path location [] to resources [file [Documents/workspace/grails/resource-bug/build/classes/groovy/main], file [Documents/workspace/grails/resource-bug/build/resources/main], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/2.0.16/9d08badad22f1ac07deac9188ade596472a2bfd9/jcl-over-slf4j-2.0.16.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/2.0.16/6d57da3e961daac65bcca0dd3def6cd11e48a24a/jul-to-slf4j-2.0.16.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.16/172931663a09a1fa515567af5fbef00897d3c04/slf4j-api-2.0.16.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.2.1/f42e6b51d9c0c2fcf95df9e5848470d173adc9af/spring-core-6.2.1.jar!/META-INF/versions/21/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/2.3/936b36210e27320f920536f695cf1af210c44586/snakeyaml-2.3.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.14.2/7ec567b052bc560ba76a95eff222fb7999b79817/micrometer-core-1.14.2.jar!/META-INF/versions/11/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.18.2/9ed6d538ebcc66864e114a7040953dce6ab6ea53/jackson-datatype-jdk8-2.18.2.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.18.2/72960cb3277347a748911d100c3302d60e8a616a/jackson-module-parameter-names-2.18.2.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.18.2/fb64ccac5c27dca8819418eb4e443a9f496d9ee7/jackson-core-2.18.2.jar!/META-INF/versions/21/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.18.2/7b6ff96adf421f4c6edbd694e797dd8fe434510a/jackson-datatype-jsr310-2.18.2.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.18.2/deef8697b92141fb6caf7aa86966cff4eec9b04f/jackson-databind-2.18.2.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.24.3/b02c125db8b6d295adf72ae6e71af5d83bce2370/log4j-api-2.24.3.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.15.5/b7a1a8a7b64d7e111d5ffc7f132d3e9addcf3888/byte-buddy-1.15.5.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.5.12/65b1fa25fe8d8e4bdc140e79eb67ac6741f775e2/logback-core-1.5.12.jar!/META-INF/versions/21/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.1/8531ad5ac454cc2deb9d4d32c40c4d7451939b5d/jaxb-api-2.3.1.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.jspecify/jspecify/1.0.0/7425a601c1c7ec76645a78d22b8c6a627edee507/jspecify-1.0.0.jar!/META-INF/versions/9/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.bertramlabs.plugins/asset-pipeline-grails/5.0.4/2131877ad2cb626c5731ecef6a290a001da2ad4b/asset-pipeline-grails-5.0.4.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-logging/7.0.0-SNAPSHOT/34d2b6233ead429abf4f99ac38c1965d0cc4064f/grails-logging-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-databinding/7.0.0-SNAPSHOT/e3f1ba3fd02106e9544e08d9fcbb957c869009df/grails-plugin-databinding-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-services/7.0.0-SNAPSHOT/ee02db98779eae976fd3370aa150430198cfd511/grails-plugin-services-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/gsp/7.0.0-SNAPSHOT/c3ecb203a279fb7df99fc8327e1e1f87a96dba66/gsp-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-interceptors/7.0.0-SNAPSHOT/e00da93fef73b4d602007a9af4eb63ee3bed3294/grails-plugin-interceptors-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/scaffolding/6.0.0-SNAPSHOT/47a677289832b9c4845d2fcf6add97a3386c34b1/scaffolding-6.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-rest/7.0.0-SNAPSHOT/4e1bbb6361fa5b0a09296bf8ef8030d860e03557/grails-plugin-rest-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-URL-mappings/7.0.0-SNAPSHOT/e869ff04fe404f3c174627241b653bba8a9886ec/grails-plugin-URL-mappings-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-controllers/7.0.0-SNAPSHOT/eaa8e43f02d3bd9acd23a77d23dc3d28f2c8ec20/grails-plugin-controllers-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-datasource/7.0.0-SNAPSHOT/66fc33222f0ac59fab94fca15fb1d55fdf125e67/grails-plugin-datasource-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-boot/7.0.0-SNAPSHOT/115fdea5f19ca37e456f7b0e1f252f7f2d2acfc4/grails-web-boot-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-i18n/7.0.0-SNAPSHOT/a2b08c50ae39399366d61a9c7d6362917014701f/grails-plugin-i18n-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-codecs/7.0.0-SNAPSHOT/6c35e8a91c5a9fb99badf3f978c188ca6d4b4cec/grails-plugin-codecs-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-mimetypes/7.0.0-SNAPSHOT/ee2167437367e5a29c61d661c96e4c125cf4ac36/grails-plugin-mimetypes-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-domain-class/7.0.0-SNAPSHOT/439f9cbfa01ac7024a4df3f59f33a9a2bb066486/grails-plugin-domain-class-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-plugin-validation/7.0.0-SNAPSHOT/9876ecc414c1db79e21c37441d89d64e4a1441f0/grails-plugin-validation-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web/7.0.0-SNAPSHOT/816a321b863882778b99a101f1cbd84d65c0c471/grails-web-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/converters/7.0.0-SNAPSHOT/8c62e9d4ca680eb7cc9227d6161ce7d2ff767e9a/converters-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-mvc/7.0.0-SNAPSHOT/37cc117283b27b9ec89a0a9d555957a949b4f289/grails-web-mvc-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/grails-plugin-sitemesh3/7.0.0-SNAPSHOT/8f8e7e2e223a131301e1cee66b80854e06abc97c/grails-plugin-sitemesh3-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-gsp-taglib/7.0.0-SNAPSHOT/7884b125e1a173dc5c5db4f9e24821b514160627/grails-web-gsp-taglib-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-jsp/7.0.0-SNAPSHOT/f1467e267806a4a8e458f98f0955d8e123fe464b/grails-web-jsp-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-gsp/7.0.0-SNAPSHOT/ef20817638c6b3945a47f27f342c87bcad67e7ba/grails-web-gsp-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-taglib/7.0.0-SNAPSHOT/b6111fcae1ebbf0f70fd7a0f34831cf90285292/grails-web-taglib-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-URL-mappings/7.0.0-SNAPSHOT/3e664e49f54d8d2abf66d1448a871e6eae4541f7/grails-web-URL-mappings-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-databinding/7.0.0-SNAPSHOT/4f28ce6bdcdfd25ff23dc86200f35bf3a11183b3/grails-web-databinding-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-web-common/7.0.0-SNAPSHOT/1238d83dfb22970963d8683bf4eedd12a6dd7c40/grails-web-common-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-gsp/7.0.0-SNAPSHOT/135fd10f30272f10aaa54c5ffa197a2fffb77463/grails-gsp-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-taglib/7.0.0-SNAPSHOT/3cd0e80c875b694a2f8e66ddc4afdbcabf7ec773/grails-taglib-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-encoder/7.0.0-SNAPSHOT/89789acdce61ef3626912887b03e103cddfcbb85/grails-encoder-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/hibernate5/9.0.0-SNAPSHOT/7608c83dc34927b86f5fcac998f1d28796c45412/hibernate5-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-gorm-support/9.0.0-SNAPSHOT/c530709ed6b38ac144bc87f1f56a7b5aa0128280/grails-datastore-gorm-support-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-core/7.0.0-SNAPSHOT/e447bf29eba3f3033785f71d9fe01652ad3da649/grails-core-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-spring/7.0.0-SNAPSHOT/78f4bc1dbd11b1de2bd9eff10fca51cf00f86fa1/grails-spring-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-bootstrap/7.0.0-SNAPSHOT/f7e7b1702c077ad08af3e0ace686eab7da035cd9/grails-bootstrap-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-web/9.0.0-SNAPSHOT/e3dff5ff4472648e046c402cab175918546ddcb7/grails-datastore-web-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-gorm-hibernate5/9.0.0-SNAPSHOT/924a9ce7c73da0bbf454e3879edc6615fd787f1/grails-datastore-gorm-hibernate5-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-gorm/9.0.0-SNAPSHOT/20badb92b970f56627f64ffd6869397756ed0ccf/grails-datastore-gorm-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-gorm-validation/9.0.0-SNAPSHOT/19ea2171ffc165a85b2f26d19d86f372a189b35f/grails-datastore-gorm-validation-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-datastore-core/9.0.0-SNAPSHOT/33fb6c4c71376114eeadf31ea55f3958028c7325/grails-datastore-core-9.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-databinding/7.0.0-SNAPSHOT/4f367177bea5a823caa4ab6f0fa767eaf539bf5/grails-databinding-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails/grails-codecs/7.0.0-SNAPSHOT/5794bb72309505880a70bd642b75308a06716675/grails-codecs-7.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.webjars.npm/bootstrap/5.3.3/b139f0b41be753e770ac1b56343c8ca4360f2947/bootstrap-5.3.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.webjars.npm/bootstrap-icons/1.11.3/6f7510f8ebe73176e9372a273ef717f1045fb3f4/bootstrap-icons-1.11.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.webjars.npm/jquery/3.7.1/abca7c4ab5c6ff5f533f5d7dbc646661c36c8b6b/jquery-3.7.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.sitemesh/spring-boot-starter-sitemesh/3.2.2/97a99e335c338e437123ec615ba68b74d8bec6d8/spring-boot-starter-sitemesh-3.2.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-actuator-autoconfigure/3.4.1/75ab4d3c257fc5b00fbfa8099ec35b6c9702b629/spring-boot-actuator-autoconfigure-3.4.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/3.4.1/f17b54cc5816ec8f06d0aca9df11c330ead97f2a/spring-boot-autoconfigure-3.4.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.h2database/h2/2.3.232/4fcc05d966ccdb2812ae8b9a718f69226c0cf4e2/h2-2.3.232.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-jdbc/10.1.34/9ff82f9a918dc5cbc8284b3f1fe30d8cda88bedc/tomcat-jdbc-10.1.34.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.fusesource.jansi/jansi/1.18/d9205bbcd4b5f9cd1effe752d18f73bd942d783f/jansi-1.18.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.github.ben-manes.caffeine/caffeine/3.1.8/24795585df8afaf70a2cd534786904ea5889c047/caffeine-3.1.8.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.groovy/groovy-templates/4.0.24/5dd5db2585048581fdf96023253e596c381d161c/groovy-templates-4.0.24.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.groovy/groovy-json/4.0.24/a735e5b44d96e17d1c370625a493e6a8a7e11be8/groovy-json-4.0.24.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.groovy/groovy-sql/4.0.24/533cc61c311ffc0e7693892b7711782b2678023/groovy-sql-4.0.24.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.groovy/groovy-xml/4.0.24/f7e9f181f9c465b4f33eb2e8b1dd2c5100c14d09/groovy-xml-4.0.24.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.groovy/groovy/4.0.24/1ebfbe13ba203625f53bab37a895954b2c160508/groovy-4.0.24.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/2.0.16/9d08badad22f1ac07deac9188ade596472a2bfd9/jcl-over-slf4j-2.0.16.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.5.12/3790d1a62e868f7915776dfb392bd9a29ce8d954/logback-classic-1.5.12.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-to-slf4j/2.24.3/da1143e2a2531ee1c2d90baa98eb50a28a39d5a7/log4j-to-slf4j-2.24.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/2.0.16/6d57da3e961daac65bcca0dd3def6cd11e48a24a/jul-to-slf4j-2.0.16.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.bertramlabs.plugins/asset-pipeline-core/5.0.4/783f1b27b362f5af309311e7b7c9a4c971e95c2a/asset-pipeline-core-5.0.4.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-ehcache/5.6.15.Final/6f312e6a7bc7acf52258b25ae949ae74728417e9/hibernate-ehcache-5.6.15.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/net.sf.ehcache/ehcache/2.10.6/38076997b10f5c762a210ea8b9f6099da35ac5f/ehcache-2.10.6.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.16/172931663a09a1fa515567af5fbef00897d3c04/slf4j-api-2.0.16.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.inject/jakarta.inject-api/2.0.1/4c28afe1991a941d7702fe1362c365f0a8641d1e/jakarta.inject-api-2.0.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-core-jakarta/5.6.15.Final/6effdb9a98e423e9faed9713e9954f093f79988c/hibernate-core-jakarta-5.6.15.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.persistence/jakarta.persistence-api/3.1.0/66901fa1c373c6aff65c13791cc11da72060a8d6/jakarta.persistence-api-3.1.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.annotation/jakarta.annotation-api/2.1.1/48b9bda22b091b1f48b13af03fe36db3be6e1ae3/jakarta.annotation-api-2.1.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-actuator/3.4.1/77873fd387c46b7bb350cc6127a3b0162c41f9bf/spring-boot-actuator-3.4.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/3.4.1/5fb9890a5eb7c4e86c8f5c0f6960b79240daf3d5/spring-boot-3.4.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-orm/6.2.1/7fd75b4984d92c3c5e46ee94365cfc79d2daa821/spring-orm-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-jdbc/6.2.1/def8d3d9bebafc36c19f8407645eddde32454c8a/spring-jdbc-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-tx/6.2.1/5ffde4fee85ff021ad613b9e86a9be893fb52572/spring-tx-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/6.2.1/44bdf7e5641d44044ac52d7bb5c1fc46004e7754/spring-webmvc-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-context-support/6.2.1/455eb5dc0c675dc49044c1518763f4c0323a5860/spring-context-support-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/6.2.1/f56c7431b03860bfdb016e68f484c5c35531ef2e/spring-context-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/6.2.1/a9384de38fc00751084446ba014a0c4962240244/spring-aop-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/6.2.1/877acb94c5b3a0c92e652b6bebdfdc7c60922ac8/spring-web-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/6.2.1/ab57ec03ba6900075bf28e3cd70ccce173205b8d/spring-beans-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/6.2.1/91fcf6b9501705c31c8337e2713fe823bb512b24/spring-expression-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.2.1/f42e6b51d9c0c2fcf95df9e5848470d173adc9af/spring-core-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-core/5.6.15.Final/ab14b7cef1fdff654ca81923048a6034d6c7cfa7/hibernate-core-5.6.15.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/4.0.5/ca84c2a7169b5293e232b9d00d1e4e36d4c3914a/jaxb-runtime-4.0.5.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-core/4.0.5/7b4b11ea5542eea4ad55e1080b23be436795b3/jaxb-core-4.0.5.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.xml.bind/jakarta.xml.bind-api/4.0.2/6cd5a999b834b63238005b7144136379dc36cad2/jakarta.xml.bind-api-4.0.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-text/1.12.0/66aa90dc099701c4d3b14bd256c328f592ccf0d6/commons-text-1.12.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.grails.plugins/fields/6.0.0-SNAPSHOT/117c4ff7a5ad7ac7198af1b13f53965038ffc358/fields-6.0.0-SNAPSHOT.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/2.3/936b36210e27320f920536f695cf1af210c44586/snakeyaml-2.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-jakarta9/1.14.2/50950404a99cde864c0e4ff3b1647e5be75d7570/micrometer-jakarta9-1.14.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.14.2/7ec567b052bc560ba76a95eff222fb7999b79817/micrometer-core-1.14.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-observation/1.14.2/a9cad29cc04c0f7e30e3e58b454d4cd47ccc54bd/micrometer-observation-1.14.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/10.1.34/eef6d430f34b6e393b8d9e40f10db9043732b4e5/tomcat-embed-websocket-10.1.34.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/10.1.34/f610f84be607fbc82e393cc220f0ad45f92afc91/tomcat-embed-core-10.1.34.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/10.1.34/d2b2daca3bc999c62e58ae36b45ba0582530fb25/tomcat-embed-el-10.1.34.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hibernate.validator/hibernate-validator/8.0.2.Final/220e64815dd87535525331de20570017f899eb13/hibernate-validator-8.0.2.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-juli/10.1.34/3e730bdbf592151765b48efe1f753ddd4de94601/tomcat-juli-10.1.34.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/txw2/4.0.5/f36a4ef12120a9bb06d766d6a0e54b144fd7ed98/txw2-4.0.5.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.sun.istack/istack-commons-runtime/4.1.2/18ec117c85f3ba0ac65409136afa8e42bc74e739/istack-commons-runtime-4.1.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.eclipse.angus/angus-activation/2.0.2/41f1e0ddd157c856926ed149ab837d110955a9fc/angus-activation-2.0.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.activation/jakarta.activation-api/2.1.3/fa165bd70cda600368eee31555222776a46b881f/jakarta.activation-api-2.1.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.18.2/9ed6d538ebcc66864e114a7040953dce6ab6ea53/jackson-datatype-jdk8-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.18.2/72960cb3277347a748911d100c3302d60e8a616a/jackson-module-parameter-names-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.18.2/fb64ccac5c27dca8819418eb4e443a9f496d9ee7/jackson-core-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.18.2/7b6ff96adf421f4c6edbd694e797dd8fe434510a/jackson-datatype-jsr310-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.18.2/985d77751ebc7fce5db115a986bc9aa82f973f4a/jackson-annotations-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.18.2/deef8697b92141fb6caf7aa86966cff4eec9b04f/jackson-databind-2.18.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.24.3/b02c125db8b6d295adf72ae6e71af5d83bce2370/log4j-api-2.24.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-commons/1.14.2/69c454dbec59c7842cf59a534b7ec03618d75b91/micrometer-commons-1.14.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.springframework/spring-jcl/6.2.1/a5d662d64470aff0ae51d210147bb6ede31a8ea3/spring-jcl-6.2.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.15.5/b7a1a8a7b64d7e111d5ffc7f132d3e9addcf3888/byte-buddy-1.15.5.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.fasterxml/classmate/1.7.0/e98374da1f2143ac8e6e0a95036994bb19137a3/classmate-1.7.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.17.1/973638b7149d333563584137ebf13a691bb60579/commons-codec-1.17.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.17.0/b17d2136f0460dcc0d2016ceefca8723bdf4ee70/commons-lang3-3.17.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.transaction/jakarta.transaction-api/2.0.1/51a520e3fae406abb84e2e1148e6746ce3f80a1a/jakarta.transaction-api-2.0.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.validation/jakarta.validation-api/3.0.2/92b6631659ba35ca09e44874d3eb936edfeee532/jakarta.validation-api-3.0.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hibernate.common/hibernate-commons-annotations/5.1.2.Final/e59ffdbc6ad09eeb33507b39ffcf287679a498c8/hibernate-commons-annotations-5.1.2.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.6.1.Final/886afbb445b4016a37c8960a7aef6ebd769ce7e5/jboss-logging-3.6.1.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.5.12/65b1fa25fe8d8e4bdc140e79eb67ac6741f775e2/logback-core-1.5.12.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/3.37.0/ba74746d38026581c12166e164bb3c15e90cc4ea/checker-qual-3.37.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.21.1/6d9b10773b5237df178a7b3c1b4208df7d0e7f94/error_prone_annotations-2.21.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.30.2-GA/284580b5e42dfa1b8267058566435d9e93fae7f7/javassist-3.30.2-GA.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/antlr/antlr/2.7.7/83cd2cd674a217ade95a4bb83a8a14f351f48bd0/antlr-2.7.7.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.jboss/jandex/2.4.2.Final/1e1c385990b258ff1a24c801e84aebbacf70eb39/jandex-2.4.2.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.dom4j/dom4j/2.1.3/a75914155a9f5808963170ec20653668a2ffd2fd/dom4j-2.1.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.glassfish/jakarta.el/4.0.2/d67e18e7b3500dc91fe941ed3a1807074eaac750/jakarta.el-4.0.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.sitemesh/sitemesh/3.2.2/d47af3d745c32df861d0a6900d6a0e0a768c4959/sitemesh-3.2.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/javax.persistence/javax.persistence-api/2.2/25665ac8c0b62f50e6488173233239120fc52c96/javax.persistence-api-2.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.jboss.spec.javax.transaction/jboss-transaction-api_1.2_spec/1.1.1.Final/a8485cab9484dda36e9a8c319e76b5cc18797b58/jboss-transaction-api_1.2_spec-1.1.1.Final.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.1/8531ad5ac454cc2deb9d4d32c40c4d7451939b5d/jaxb-api-2.3.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/javax.activation/javax.activation-api/1.2.0/85262acf3ca9816f9537ca47d5adeabaead7cb16/javax.activation-api-1.2.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/commons-validator/commons-validator/1.9.0/26e49d333890ccad072eb530a85fceb9c07818df/commons-validator-1.9.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.2.2/7959933ebcc0f05b2eaa5af0a0c8689fa257b15c/HdrHistogram-2.2.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.latencyutils/LatencyUtils/2.0.3/769c0b82cb2421c8256300e907298a9410a2a3d3/LatencyUtils-2.0.3.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/jakarta.el/jakarta.el-api/4.0.0/ba9834bd2dba5014072bacbafecffaec1673b0f9/jakarta.el-api-4.0.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.google.javascript/closure-compiler-unshaded/v20240317/99d0e978e433293899988a8e40c98af3732dd518/closure-compiler-unshaded-v20240317.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.jspecify/jspecify/1.0.0/7425a601c1c7ec76645a78d22b8c6a627edee507/jspecify-1.0.0.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.graalvm.sdk/graal-sdk/24.1.1/7089d884d049f8337ffd316044049a1689ef5b6c/graal-sdk-24.1.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.graalvm.js/js-scriptengine/24.1.1/dfbc0ff53b66822f39742687378844192330889c/js-scriptengine-24.1.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.graalvm.js/js-community/24.1.1/3e874f113d724138c39287df69e5cfb7e5fcf700/js-community-24.1.1.pom!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/org.graalvm.js/js-language/24.1.1/9ce77f1ec321656a8eb0eb7e3183778ca624078a/js-language-24.1.1.jar!/], 
URL [jar:file:.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar!/]]
```

What is findbugs doing in the class path?? `jsr305-3.0.2.jar` but no geb or selenium??

**Comment by jdaugherty** [comment]
Findbugs is there because of `com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava` which is there because somehow the bom itself is being exported as a dependency for the integration test scope instead of as a platform.

**Comment by matrei** [comment]
Could `asset-pipeline-gradle` be the source of this? It seems to be doing stuff with the `bootRun` `runtimeClasspath`.
https://github.com/bertramdev/asset-pipeline/blob/905f3992c83c2193954348e2feefc14bb016c7ea/asset-pipeline-gradle/src/main/groovy/asset/pipeline/gradle/AssetPipelinePlugin.groovy#L42

**Comment by jdaugherty** [comment]
I removed the asset plugin and ran `./gradlew dependencies` - it still shows that dependency in the integration classpath, so I don't think it's the asset plugin causing this.

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/pull/13992

**Comment by jdaugherty** [comment]
@codeconsole isn't this fixed with the asset pipeline release?

**Comment by codeconsole** [comment]
@jdaugherty yes

**Comment by matrei** [comment]
https://github.com/spring-projects/spring-framework/issues/34417
