### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by flofreud** [grails/grails-core#9879]
Execution of Grails on a machine which has no cached dependencies of this Grails version is currently not working anymore. When starting the grails console in a grails app (tested with 3.0.15, 3.0.16 and 3.1.5) the following error appears (with matching versions):

```
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not determine artifacts for org.grails:grails-dependencies:3.1.5
      > Could not get resource 'https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.5/grails-dependencies-3.1.5.jar'.
         > Could not HEAD 'https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.5/grails-dependencies-3.1.5.jar'. Received status code 409 from server: Conflict
```

Last friday it was still working. On systems which executed the grails version already, it is working. Happens also for newly created apps.

**Comment by flofreud** [comment]
Issue was observed on Windows and MacOS maschines on different european locations.

**Comment by dandonmesvak** [comment]
Same on Ubuntu 14.04.
Might be because of a failed deploy to JFrog Artifactory. You get 409 if you navigate to any of the following URLs:

1. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.0/grails-dependencies-3.1.0.jar
2. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.1/grails-dependencies-3.1.1.jar
3. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.2/grails-dependencies-3.1.2.jar
4. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.3/grails-dependencies-3.1.3.jar
5. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.4/grails-dependencies-3.1.4.jar
6. https://repo.grails.org/grails/core/org/grails/grails-dependencies/3.1.5/grails-dependencies-3.1.5.jar


There is also a stackoverflow question on this: http://stackoverflow.com/questions/36677477/grails-on-ubuntu-14-04-lts-with-strange-error-3-1-5-grails-dependencies-3-1

**Comment by DialloAbdourahamane** [comment]
I  have the same error on MacOsx with web profile, but when i create a new app with rest-app profile everything work fine.

**Comment by nourlan** [comment]
The same error on Linux Debian amd64 (wheezy). JDK 1.8, grails 3.1.5, gradle 2.12

**Comment by helgew** [comment]
FWIW - this is the full response at the server:
`{
  "errors" : [ {
    "status" : 409,
    "message" : "The repository 'libs-snapshots-local' rejected the artifact 'libs-snapshots-local:org/grails/grails-dependencies/3.1.5/grails-dependencies-3.1.5.jar' due to its snapshot/release handling policy."
  } ]
}`

**Comment by donald-jackson** [comment]
This is happening to me as well - looks like something is wrong with the repo

**Comment by erikahlswede** [comment]
Confirmed.  Seems like a maven issue
Grails 3.1.5
OS:	Ubuntu 14.04 LTS
Codename:	trusty

**Comment by danielwalker** [comment]
Ditto, all 3.x versions appear to be effected. All builds requiring dependencies from repo.grails.org failing.

**Comment by ajscilingo** [comment]
I too am seeing this error trying to build a project that requires grails through a jenkins server

**Comment by kwkhaw** [comment]
We saw this problem using Grails 2.4.3 as well.

`{
"errors": [
{
"status": 409,
"message": "The repository 'libs-snapshots-local' rejected the artifact 'libs-snapshots-local:org/grails/grails-dependencies/2.4.3/grails-dependencies-2.4.3.jar' due to its snapshot/release handling policy."
}
]
}`

**Comment by graemerocher** [comment]
We are investigating the problem, very odd since I can understand the error as `grails-dependencies` is not a JAR file it is a POM only dependency

**Comment by nourlan** [comment]
The error appear when I create empty application with grails utility. The error appears too when I try to create app with Idea 14 IDE using build.gradle.
Please support with your ideas.

**Comment by graemerocher** [comment]
The problem should be fixed now, although in order to fix it I had to disable the ability to resolve any snapshots from https://repo.grails.org/grails/core/ which may break some builds if you depend on snapshots

I am investigating restoring the ability to resolve snapshots from there, in the meantime you can use https://repo.grails.org/grails/snapshots for snapshots of plugins or GORM or whatever

**Comment by nourlan** [comment]
Thanks, default profile is ok, but rest-api profile shows above text (not ususal web-page).

**Comment by graemerocher** [comment]
@nourlan I'm not sure which text you refer to, that is the JSON response from the REST profile and is there by design

**Comment by kwkhaw** [comment]
@graemerocher Thanks!
Just an update from my side. Our Jenkins build still fail.
`Could not resolve all dependencies for configuration ':runtime'.
> Could not determine artifacts for component 'org.grails:grails-dependencies:2.4.3'
   > Could not HEAD 'http://repo.grails.org/grails/repo/org/grails/grails-dependencies/2.4.3/grails-dependencies-2.4.3.jar'. Received status code 409 from server: Conflict`

**Comment by graemerocher** [comment]
@kwkhaw you seem to be using a different repo to `core`, I will check that one

**Comment by graemerocher** [comment]
@kwkhaw In the meantime I suggest changing from `https://repo.grails.org/grails/repo/` to `https://repo.grails.org/grails/core/`

**Comment by kwkhaw** [comment]
@graemerocher Thanks!
We are using grails-gradle-plugin, and this is specified in our build.gradle
`repositories {
  grails.central() //creates a maven repo for the Grails Central repository (Core libraries and plugins)
  mavenCentral()
  maven { url "http://repository-saucelabs.forge.cloudbees.com/release" }
  maven { url "http://repo.grails.org/grails/core" }
}`
mmm... probably it is hardcoded in grails-gradle-plugin?

**Comment by kwkhaw** [comment]
Update:
After moving the `https://repo.grails.org/grails/core` to the top, it works now. :-)
```
repositories {
  maven { url "http://repo.grails.org/grails/core" }
  grails.central() //creates a maven repo for the Grails Central repository (Core libraries and plugins)
  mavenCentral()
  maven { url "http://repository-saucelabs.forge.cloudbees.com/release" }
}
```

**Comment by DialloAbdourahamane** [comment]
@graemerocher   Creating grails web profile and rest-api  profile  on grails 3.1.5 work fine now for me, thks.

**Comment by nourlan** [comment]
When I use grails utility to run app - everything is ok. But when I try to run app from IDE (Idea 14) I receive the following error:
type Exception report

message javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
	grails.plugin.cache.web.filter.AbstractFilter.logThrowable(AbstractFilter.java:116)
	grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:70)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:75)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:113)
	org.springframework.boot.context.web.ErrorPageFilter.forwardToErrorPage(ErrorPageFilter.java:188)
	org.springframework.boot.context.web.ErrorPageFilter.handleException(ErrorPageFilter.java:171)
	org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:135)
	org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:61)
	org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:95)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:113)

**Comment by graemerocher** [comment]
Seems unrelated to the dependency problem described in this issue, please ask questions in Slack
